# Generated by Django 3.2.19 on 2023-06-22 08:11

import My_plant_project.my_plant_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_plant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[My_plant_project.my_plant_app.models.validate_string_starts_with_capital_letter])),
                ('last_name', models.CharField(max_length=20, validators=[My_plant_project.my_plant_app.models.validate_string_starts_with_capital_letter])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
