# Generated by Django 3.2.19 on 2023-06-22 12:53

import My_plant_project.my_plant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_app', '0004_auto_20230622_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[My_plant_project.my_plant_app.models.validate_string_starts_with_capital_letter], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[My_plant_project.my_plant_app.models.validate_string_starts_with_capital_letter], verbose_name='Last Name'),
        ),
    ]
