# Generated by Django 3.2.19 on 2023-06-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_app', '0007_remove_plant_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ('pk',)},
        ),
    ]
